insert into estacion (nombre, direccion) values ('Kingsford', '24213 Debra Road');
insert into estacion (nombre, direccion) values ('5th', '5880 Village Green Park');
insert into estacion (nombre, direccion) values ('Shasta', '559 Hanover Crossing');
insert into estacion (nombre, direccion) values ('Eagle Crest', '025 Division Trail');
insert into estacion (nombre, direccion) values ('Carpenter', '52 Warner Lane');
insert into estacion (nombre, direccion) values ('Garrison', '6 Waxwing Court');
insert into estacion (nombre, direccion) values ('4th', '3 Johnson Park');
insert into estacion (nombre, direccion) values ('Brentwood', '20653 Buhler Plaza');
insert into estacion (nombre, direccion) values ('Di Loreto', '5890 Dexter Lane');
insert into estacion (nombre, direccion) values ('Mccormick', '824 Oxford Street');
insert into estacion (nombre, direccion) values ('Clarendon', '93 Elgar Court');
insert into estacion (nombre, direccion) values ('Village Green', '5 Elka Center');
insert into estacion (nombre, direccion) values ('Almo', '37 Pepper Wood Point');
insert into estacion (nombre, direccion) values ('Morrow', '9 Dawn Pass');
insert into estacion (nombre, direccion) values ('Badeau', '3 Autumn Leaf Center');
insert into estacion (nombre, direccion) values ('Nobel', '7 Raven Avenue');
insert into estacion (nombre, direccion) values ('Fremont', '6013 Oak Street');
insert into estacion (nombre, direccion) values ('Beilfuss', '607 Raven Terrace');
insert into estacion (nombre, direccion) values ('Troy', '2 Londonderry Parkway');
insert into estacion (nombre, direccion) values ('Lyons', '7 Portage Crossing');
insert into estacion (nombre, direccion) values ('Esch', '134 Warbler Plaza');
insert into estacion (nombre, direccion) values ('American Ash', '2 East Alley');
insert into estacion (nombre, direccion) values ('Melrose', '37 South Trail');
insert into estacion (nombre, direccion) values ('Nobel', '4 Esch Circle');
insert into estacion (nombre, direccion) values ('Farragut', '614 Saint Paul Parkway');
insert into estacion (nombre, direccion) values ('High Crossing', '0884 Oak Pass');
insert into estacion (nombre, direccion) values ('Oak', '4 Victoria Avenue');
insert into estacion (nombre, direccion) values ('Spohn', '5 Artisan Park');
insert into estacion (nombre, direccion) values ('Darwin', '2140 Claremont Pass');
insert into estacion (nombre, direccion) values ('Grim', '2970 Transport Pass');
insert into estacion (nombre, direccion) values ('Thackeray', '0 Brown Alley');
insert into estacion (nombre, direccion) values ('Debra', '29 Mallory Lane');
insert into estacion (nombre, direccion) values ('Hayes', '85 Nancy Center');
insert into estacion (nombre, direccion) values ('Kipling', '6 Eggendart Road');
insert into estacion (nombre, direccion) values ('Anthes', '25635 Redwing Plaza');
insert into estacion (nombre, direccion) values ('Jenna', '43 Meadow Vale Way');
insert into estacion (nombre, direccion) values ('Eastlawn', '8 Rigney Circle');
insert into estacion (nombre, direccion) values ('Delladonna', '6 Sutteridge Center');
insert into estacion (nombre, direccion) values ('Mccormick', '512 Main Road');
insert into estacion (nombre, direccion) values ('Johnson', '8 Ridge Oak Alley');
insert into estacion (nombre, direccion) values ('Kropf', '41 Loeprich Avenue');
insert into estacion (nombre, direccion) values ('Forest Run', '2 Park Meadow Point');
insert into estacion (nombre, direccion) values ('Coolidge', '81429 Mandrake Pass');
insert into estacion (nombre, direccion) values ('Mendota', '585 Homewood Way');
insert into estacion (nombre, direccion) values ('Lillian', '859 Columbus Place');
insert into estacion (nombre, direccion) values ('Summit', '5436 Butterfield Center');
insert into estacion (nombre, direccion) values ('Florence', '73836 Waxwing Court');
insert into estacion (nombre, direccion) values ('Melrose', '319 Northridge Junction');
insert into estacion (nombre, direccion) values ('Lawn', '739 Maryland Court');
insert into estacion (nombre, direccion) values ('Mariners Cove', '03 Sunfield Trail');
insert into estacion (nombre, direccion) values ('Bonner', '4 Southridge Terrace');
insert into estacion (nombre, direccion) values ('Cordelia', '3 Schurz Avenue');
insert into estacion (nombre, direccion) values ('Del Mar', '6527 Dennis Center');
insert into estacion (nombre, direccion) values ('Ronald Regan', '327 Lighthouse Bay Circle');
insert into estacion (nombre, direccion) values ('Jay', '356 Basil Hill');
insert into estacion (nombre, direccion) values ('Merrick', '346 Mockingbird Place');
insert into estacion (nombre, direccion) values ('Delaware', '838 Warbler Drive');
insert into estacion (nombre, direccion) values ('Anderson', '850 Westridge Point');
insert into estacion (nombre, direccion) values ('Loeprich', '80046 Hoepker Circle');
insert into estacion (nombre, direccion) values ('Blackbird', '89311 Hallows Pass');
insert into estacion (nombre, direccion) values ('Lien', '8 Blackbird Junction');
insert into estacion (nombre, direccion) values ('Eggendart', '923 Buhler Avenue');
insert into estacion (nombre, direccion) values ('Cambridge', '6 Carioca Road');
insert into estacion (nombre, direccion) values ('Oriole', '3 Darwin Center');
insert into estacion (nombre, direccion) values ('Homewood', '24737 7th Park');
insert into estacion (nombre, direccion) values ('Kropf', '3810 Dwight Avenue');
insert into estacion (nombre, direccion) values ('Rigney', '7318 Clyde Gallagher Circle');
insert into estacion (nombre, direccion) values ('Ridgeway', '14 Walton Circle');
insert into estacion (nombre, direccion) values ('Mallard', '03 Annamark Place');
insert into estacion (nombre, direccion) values ('Bayside', '39 Columbus Court');
insert into estacion (nombre, direccion) values ('Dixon', '0636 Upham Crossing');
insert into estacion (nombre, direccion) values ('1st', '790 Hanson Circle');
insert into estacion (nombre, direccion) values ('Warbler', '3 Crowley Junction');
insert into estacion (nombre, direccion) values ('8th', '01 Aberg Point');
insert into estacion (nombre, direccion) values ('Brown', '11615 Dryden Lane');
insert into estacion (nombre, direccion) values ('Anthes', '9 Rigney Street');
insert into estacion (nombre, direccion) values ('Kenwood', '289 Hanson Plaza');
insert into estacion (nombre, direccion) values ('Fieldstone', '46345 Nancy Hill');
insert into estacion (nombre, direccion) values ('Fieldstone', '38 Arkansas Point');
insert into estacion (nombre, direccion) values ('Del Mar', '3 Buena Vista Court');
insert into estacion (nombre, direccion) values ('Thompson', '03611 Fulton Point');
insert into estacion (nombre, direccion) values ('Melvin', '12 Surrey Plaza');
insert into estacion (nombre, direccion) values ('American Ash', '51 Forest Run Trail');
insert into estacion (nombre, direccion) values ('Onsgard', '4978 Magdeline Street');
insert into estacion (nombre, direccion) values ('Everett', '6379 Briar Crest Avenue');
insert into estacion (nombre, direccion) values ('Ridge Oak', '43 Pond Alley');
insert into estacion (nombre, direccion) values ('Mayer', '0346 Stone Corner Hill');
insert into estacion (nombre, direccion) values ('Weeping Birch', '06 Lillian Pass');
insert into estacion (nombre, direccion) values ('Longview', '72 Doe Crossing Drive');
insert into estacion (nombre, direccion) values ('Anniversary', '84 Hauk Way');
insert into estacion (nombre, direccion) values ('Fulton', '600 Goodland Road');
insert into estacion (nombre, direccion) values ('Moland', '0404 Fairfield Alley');
insert into estacion (nombre, direccion) values ('Meadow Vale', '36886 Prairie Rose Place');
insert into estacion (nombre, direccion) values ('Paget', '939 Cambridge Avenue');
insert into estacion (nombre, direccion) values ('Little Fleur', '3621 Kennedy Parkway');
insert into estacion (nombre, direccion) values ('Bluestem', '2 Walton Drive');
insert into estacion (nombre, direccion) values ('Hoepker', '15394 Duke Center');
insert into estacion (nombre, direccion) values ('New Castle', '72635 Ridgeview Crossing');
insert into estacion (nombre, direccion) values ('Ohio', '0 Florence Way');
insert into estacion (nombre, direccion) values ('Forest Dale', '8 Melody Park');
