insert into tren (modelo, capacidad) values ('Eclipse', 1);
insert into tren (modelo, capacidad) values ('Tacoma', 2);
insert into tren (modelo, capacidad) values ('2500 Club Coupe', 3);
insert into tren (modelo, capacidad) values ('Swift', 4);
insert into tren (modelo, capacidad) values ('F350', 5);
insert into tren (modelo, capacidad) values ('Outback Sport', 6);
insert into tren (modelo, capacidad) values ('VS Commodore', 7);
insert into tren (modelo, capacidad) values ('Golf', 8);
insert into tren (modelo, capacidad) values ('Tiburon', 9);
insert into tren (modelo, capacidad) values ('V50', 10);
insert into tren (modelo, capacidad) values ('Tucson', 11);
insert into tren (modelo, capacidad) values ('NSX', 12);
insert into tren (modelo, capacidad) values ('Sonata', 13);
insert into tren (modelo, capacidad) values ('LS', 14);
insert into tren (modelo, capacidad) values ('2500', 15);
insert into tren (modelo, capacidad) values ('Stratus', 16);
insert into tren (modelo, capacidad) values ('Equinox', 17);
insert into tren (modelo, capacidad) values ('CR-V', 18);
insert into tren (modelo, capacidad) values ('MR2', 19);
insert into tren (modelo, capacidad) values ('Sunbird', 20);
insert into tren (modelo, capacidad) values ('GTI', 21);
insert into tren (modelo, capacidad) values ('Eclipse', 22);
insert into tren (modelo, capacidad) values ('Aerostar', 23);
insert into tren (modelo, capacidad) values ('LeMans', 24);
insert into tren (modelo, capacidad) values ('S-Series', 25);
insert into tren (modelo, capacidad) values ('I', 26);
insert into tren (modelo, capacidad) values ('Neon', 27);
insert into tren (modelo, capacidad) values ('E150', 28);
insert into tren (modelo, capacidad) values ('Horizon', 29);
insert into tren (modelo, capacidad) values ('Caliber', 30);
insert into tren (modelo, capacidad) values ('MX-6', 31);
insert into tren (modelo, capacidad) values ('Q', 32);
insert into tren (modelo, capacidad) values ('Escort', 33);
insert into tren (modelo, capacidad) values ('Topaz', 34);
insert into tren (modelo, capacidad) values ('Leganza', 35);
insert into tren (modelo, capacidad) values ('Thunderbird', 36);
insert into tren (modelo, capacidad) values ('F250', 37);
insert into tren (modelo, capacidad) values ('Avalanche', 38);
insert into tren (modelo, capacidad) values ('Thunderbird', 39);
insert into tren (modelo, capacidad) values ('Ranger', 40);
insert into tren (modelo, capacidad) values ('Fox', 41);
insert into tren (modelo, capacidad) values ('Ram Wagon B250', 42);
insert into tren (modelo, capacidad) values ('Jimmy', 43);
insert into tren (modelo, capacidad) values ('TT', 44);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 45);
insert into tren (modelo, capacidad) values ('240SX', 46);
insert into tren (modelo, capacidad) values ('Mazda6', 47);
insert into tren (modelo, capacidad) values ('Sierra 3500', 48);
insert into tren (modelo, capacidad) values ('3500', 49);
insert into tren (modelo, capacidad) values ('TT', 50);
insert into tren (modelo, capacidad) values ('Caprice', 51);
insert into tren (modelo, capacidad) values ('6000', 52);
insert into tren (modelo, capacidad) values ('Sportage', 53);
insert into tren (modelo, capacidad) values ('Eldorado', 54);
insert into tren (modelo, capacidad) values ('Savana 3500', 55);
insert into tren (modelo, capacidad) values ('Forester', 56);
insert into tren (modelo, capacidad) values ('Savana 1500', 57);
insert into tren (modelo, capacidad) values ('F250', 58);
insert into tren (modelo, capacidad) values ('Galant', 59);
insert into tren (modelo, capacidad) values ('Mystique', 60);
insert into tren (modelo, capacidad) values ('S-Class', 61);
insert into tren (modelo, capacidad) values ('Durango', 62);
insert into tren (modelo, capacidad) values ('Tiburon', 63);
insert into tren (modelo, capacidad) values ('Optima', 64);
insert into tren (modelo, capacidad) values ('Esprit', 65);
insert into tren (modelo, capacidad) values ('80', 66);
insert into tren (modelo, capacidad) values ('DTS', 67);
insert into tren (modelo, capacidad) values ('Yukon', 68);
insert into tren (modelo, capacidad) values ('Suburban 2500', 69);
insert into tren (modelo, capacidad) values ('Envoy', 70);
insert into tren (modelo, capacidad) values ('MX-5', 71);
insert into tren (modelo, capacidad) values ('Raider', 72);
insert into tren (modelo, capacidad) values ('F150', 73);
insert into tren (modelo, capacidad) values ('Acclaim', 74);
insert into tren (modelo, capacidad) values ('6000', 75);
insert into tren (modelo, capacidad) values ('C30', 76);
insert into tren (modelo, capacidad) values ('F350', 77);
insert into tren (modelo, capacidad) values ('NSX', 78);
insert into tren (modelo, capacidad) values ('600', 79);
insert into tren (modelo, capacidad) values ('Cayman', 80);
insert into tren (modelo, capacidad) values ('Corvette', 81);
insert into tren (modelo, capacidad) values ('Sierra 2500', 82);
insert into tren (modelo, capacidad) values ('Cayenne', 83);
insert into tren (modelo, capacidad) values ('Diamante', 84);
insert into tren (modelo, capacidad) values ('CL-Class', 85);
insert into tren (modelo, capacidad) values ('Fit', 86);
insert into tren (modelo, capacidad) values ('Savana Cargo Van', 87);
insert into tren (modelo, capacidad) values ('Range Rover', 88);
insert into tren (modelo, capacidad) values ('Sixty Special', 89);
insert into tren (modelo, capacidad) values ('Marquis', 90);
insert into tren (modelo, capacidad) values ('Quest', 91);
insert into tren (modelo, capacidad) values ('VUE', 92);
insert into tren (modelo, capacidad) values ('Montego', 93);
insert into tren (modelo, capacidad) values ('88', 94);
insert into tren (modelo, capacidad) values ('Carrera GT', 95);
insert into tren (modelo, capacidad) values ('300M', 96);
insert into tren (modelo, capacidad) values ('Passport', 97);
insert into tren (modelo, capacidad) values ('XC70', 98);
insert into tren (modelo, capacidad) values ('62', 99);
insert into tren (modelo, capacidad) values ('Regal', 100);
